spring:
  profiles:
    active: default


---

server:
  port: 8085

---
spring:
  main:
    web-application-type: reactive

  r2dbc:
    url: r2dbc:postgresql://localhost:5434/postgres?currentSchema=mg-usr
    username: careered
    password: amar1404

---
logging:
  level:
    root: INFO
    org.springframework: DEBUG